### ISSUE TITLE
startStructFetch with undefined structId 

### ISSUE THREAD

**Issue by ghost** [Qlean/redux-struct#2]
I think we should add some checks on `startStructFetch` argument in order to prevent creating sturcts like
```
undefined: {
  data: null,
  error: null,
  isFetching: false,
}
```

**Comment by atiupin** [comment]
Yeah, only strings and numbers should be correct struct ids.

**Comment by atiupin** [comment]
https://github.com/Qlean/redux-struct/pull/8
