### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by ghost** [Qlean/redux-struct#3]
In the section 4 there is
```js
import { getStruct } from 'utils/sagas';
```
and API has `getStruct` method with following signature `getStruct :: (t1, t) -> t -> t2` which is differ from `getStruct` imported from `utils/sagas`;

Could you please add how `getStruct` from `utils/sagas` looks like?

**Comment by atiupin** [comment]
It's a error. Should be:
```js
import { getStruct } from 'redux-scruct';

const mapStateToProps = (state, props) => {
  const { userId } = props;
  return {
    user: getStruct(userId)(state),
  };
}
```
